# Generated by Django 6.0.2 on 2026-02-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch',
        ),
    ]
