# Generated by Django 6.0.2 on 2026-02-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch',
            field=models.CharField(default='B000', max_length=50),
            preserve_default=False,
        ),
    ]
