# Generated by Django 6.0.2 on 2026-02-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_transaction_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
